import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";

export const metadata: Metadata = {
  title: "Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" min-h-screen bg-black overflow-hidden text-white items-center justify-center inset-0 bg-gradient-to-r from-[#000000] via-[#1f0036] to-[#0a0a0a] bg-size-400 animate-gradient opacity-80">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
